name: Docker Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Node.js dependencies
        run: npm install

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build Docker image
        run: docker build -t smuzoo/demoapp .

      - name: Set date variable
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./path/to/Dockerfile
          push: true
          tags: |
            smuzoo/demoapp:latest
            smuzoo/demoapp:1.0.0-${{ steps.date.outputs.date }}
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy using docker-compose
        run: docker-compose up -d
        working-directory: .